### ISSUE TITLE
Error in /pics command

### ISSUE THREAD

**Issue by truki** [truki/ArasaacBot#15]
When  try /pics gorra --> choose ESP --> choose contains

```
2017-07-19 12:14:28,938 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/callbackqueryhandler.py", line 107, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/trukise/hack/python/ArasaacBot/commands/pictos.py", line 235, in getPics_stage3_search
    pictograms = getPictosFromQuery(word, color, language, search)
  File "/home/trukise/hack/python/ArasaacBot/commands/pictos.py", line 63, in getPictosFromQuery
    catalog == 'bwpictos'
UnboundLocalError: local variable 'catalog' referenced before assignment

```

**Comment by truki** [comment]
Solved!! 63e7c214326ea2ab9023c130cb74ca59f7a5eba0
