### ISSUE TITLE
Error /picsBW carro

### ISSUE THREAD

**Issue by truki** [truki/ArasaacBot#8]
2017-06-02 12:15:21,964 - commands.pictos - INFO - /getPicsBW MP3: http://www.arasaac.org/repositorio/locuciones/0/6662.mp3
2017-06-02 12:15:22,781 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 100, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/trukise/hack/python/ArasaacBot/commands/pictos.py", line 119, in getPictosBW
    logger.info("/getPicsBW MP3: {}".format(picto['soundMP3URL']))
KeyError: 'soundMP3URL'

**Comment by truki** [comment]
solved with 342a9beca7701cb32541715800914e8f0086dd5b
